# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    gnumakefile                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hlimouni <hlimouni@student.1337.ma>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/12/26 21:52:28 by hlimouni          #+#    #+#              #
#    Updated: 2021/01/20 12:26:00 by hlimouni         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC=gcc
CFLAGS=-Wall -Wextra -Werror
NAME=miniRT
PARSER=parser
VPATH=libft:get_next_line:parser:mlx:t_vector_math

HEADER=minirt.h

SRC=\

SRCPARSER=\

LIBFT=libft.a
LIBMLX=libmlx.dylib

OBJ=$(SRC:.c=.o)

all: $(NAME)

$(NAME) : $(LIBFT) $(OBJ) $(SRCPARSER) 
	$(AR) $(ARFLAGS) $(NAME) $(OBJ) $(OBJLIBFT)

$(OBJ) : %.o : %.c 
	$(CC) $(CFLAGS) -c $< -o $@

$(LIBFT) : 

$(OBJLIBFT) : %.o : %.c
	make -C libft

clean :
	make clean -C mlx
	make clean -C libft
	rm -f $(OBJ)

fclean : clean
	make fclean -C libft
	rm -f $(NAME)

re : fclean all

